### 참석자 전체 조회
@reservationId = 2
GET http://localhost:8080/api/attendees/{{reservationId}}

### 폼 링크 통한 참석자 등록
@token =
POST http://localhost:8080/api/attendees?token={{token}}
Content-Type: application/json

{
  "name": "2테스트2",
  "email": "khyeon2021@kyonggi.ac.kr",
  "phone": "010-12345-5678",
  "birth": null
}

### 참석자 정보 수정
@attendeeId = 5
PATCH http://localhost:8080/api/attendees/{{attendeeId}}
Content-Type: application/json

{
  "reservationId": 2,
  "name": "1테스트",
  "email": "khyeon2020@naver.com",
  "phone": "010-1111-3333"
}