@access_token=eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIzNSIsImVtYWlsIjoiYWRtaW40QGZhaXJwbGF5LmNvbSIsInJvbGUiOiLsoITssrQg6rSA66as7J6QIiwiaWF0IjoxNzU0NTQxMjY2LCJleHAiOjE3NTQ1NDE4NjZ9.cLU0641jJeY-3jj54oS-eZhVosylaiFEQ6D4sT0zUIk

### 행사 등록
POST http://localhost:8080/api/events
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "email": "postmalone@fairplay.com",
  "titleKr": "포스트 말론 2025 내한 공연",
  "titleEng": "POST MALONE LIVE in SEOUL 2025",
  "hidden": false
}

### 행사 상세 등록
@createEventDetailId=8
POST http://localhost:8080/api/events/{{createEventDetailId}}/details
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "address": "서울 구로구 경인로 430",
  "placeName": "고척스카이돔",
  "longitude": 126.867104761712,
  "latitude": 37.4982338495579,
  "placeUrl": "http://place.map.kakao.com/7890664",
  "locationDetail": "고척스카이돔",
  "bio": "전 세계가 주목한 슈퍼스타와 서울에서 만나는 기회!",
  "content": "포스트 말론(Post Malone)이 드디어 한국을 찾습니다. 그래미 어워드 후보에 10번 노미네이트되며 전 세계적으로 사랑받는 아티스트의 라이브 무대를 고척스카이돔에서 만나보세요. \n 히트곡 'Circles', 'Sunflower', 'Rockstar' 등 수많은 명곡들을 라이브로 들을 수 있는 특별한 기회입니다. 포스트 말론만의 독특한 음악 스타일과 카리스마 넘치는 퍼포먼스를 직접 경험해보세요.",
  "policy": "본 공연은 청소년관람불가 등급입니다.\n 공연 시작 후 입장이 제한될 수 있습니다.",
  "eventTime": 180,
  "thumbnailUrl": "/images/malone.jpg",
  "startDate": "2025-08-25",
  "endDate": "2025-08-26",
  "mainCategoryId": 4,
  "subCategoryId": 401,
  "reentryAllowed": false,
  "checkOutAllowed": false
}


### 행사 목록 조회 (메인페이지)
GET http://localhost:8080/api/events
Accept: application/json

### 행사 목록 조회 (검색용)
GET http://localhost:8080/api/events?keyword=콘서트&mainCategoryId=4&regionName=서울&fromDate=2025-08-01&toDate=2025-10-31
Accept: application/json


### 행사 목록 조회 (행사 정보 리스트)
GET http://localhost:8080/api/events/list
Accept: application/json

### 행사 상세 조회
@readEventDetailId = 1015
GET http://localhost:8080/api/events/{{readEventDetailId}}/details
Accept: application/json


### 행사명 및 숨김 상태 업데이트
@updateEventId = 4
PATCH http://localhost:8080/api/events/{{updateEventId}}
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "hidden": false
}

### 행사 상세 업데이트
@updateEventDetailId = 1
PATCH http://localhost:8080/api/events/{{updateEventDetailId}}/details
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "thumbnailUrl": "/images/gd2.png"
}

### 행사 삭제
@deleteEventId = 1021
DELETE http://localhost:8080/api/events/{{deleteEventId}}
Authorization: Bearer {{access_token}}

### 행사 강제 삭제
DELETE http://localhost:8080/api/events/{{deleteEventId}}/force
Authorization: Bearer {{access_token}}